// Generated by gencpp from file task3/coords_2d_array.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_COORDS_2D_ARRAY_H
#define TASK3_MESSAGE_COORDS_2D_ARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <task3/coords_2d.h>

namespace task3
{
template <class ContainerAllocator>
struct coords_2d_array_
{
  typedef coords_2d_array_<ContainerAllocator> Type;

  coords_2d_array_()
    : points()  {
    }
  coords_2d_array_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::task3::coords_2d_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::task3::coords_2d_<ContainerAllocator> >> _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::task3::coords_2d_array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task3::coords_2d_array_<ContainerAllocator> const> ConstPtr;

}; // struct coords_2d_array_

typedef ::task3::coords_2d_array_<std::allocator<void> > coords_2d_array;

typedef boost::shared_ptr< ::task3::coords_2d_array > coords_2d_arrayPtr;
typedef boost::shared_ptr< ::task3::coords_2d_array const> coords_2d_arrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task3::coords_2d_array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task3::coords_2d_array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task3::coords_2d_array_<ContainerAllocator1> & lhs, const ::task3::coords_2d_array_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task3::coords_2d_array_<ContainerAllocator1> & lhs, const ::task3::coords_2d_array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::task3::coords_2d_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task3::coords_2d_array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task3::coords_2d_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task3::coords_2d_array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task3::coords_2d_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task3::coords_2d_array_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task3::coords_2d_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0083ddac30f807eeef29c66ffedb79c7";
  }

  static const char* value(const ::task3::coords_2d_array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0083ddac30f807eeULL;
  static const uint64_t static_value2 = 0xef29c66ffedb79c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::task3::coords_2d_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task3/coords_2d_array";
  }

  static const char* value(const ::task3::coords_2d_array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task3::coords_2d_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task3/coords_2d[] points\n"
"================================================================================\n"
"MSG: task3/coords_2d\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::task3::coords_2d_array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task3::coords_2d_array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct coords_2d_array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task3::coords_2d_array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task3::coords_2d_array_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::task3::coords_2d_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK3_MESSAGE_COORDS_2D_ARRAY_H
