// Generated by gencpp from file task2/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TASK2_MESSAGE_ADDTWOINTS_H
#define TASK2_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <task2/AddTwoIntsRequest.h>
#include <task2/AddTwoIntsResponse.h>


namespace task2
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace task2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task2::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::task2::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::task2::AddTwoInts > {
  static const char* value()
  {
    return "task2/AddTwoInts";
  }

  static const char* value(const ::task2::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::task2::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::task2::AddTwoInts >
template<>
struct MD5Sum< ::task2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task2::AddTwoInts >::value();
  }
  static const char* value(const ::task2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task2::AddTwoIntsRequest> should match
// service_traits::DataType< ::task2::AddTwoInts >
template<>
struct DataType< ::task2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::task2::AddTwoInts >::value();
  }
  static const char* value(const ::task2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task2::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::task2::AddTwoInts >
template<>
struct MD5Sum< ::task2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task2::AddTwoInts >::value();
  }
  static const char* value(const ::task2::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task2::AddTwoIntsResponse> should match
// service_traits::DataType< ::task2::AddTwoInts >
template<>
struct DataType< ::task2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::task2::AddTwoInts >::value();
  }
  static const char* value(const ::task2::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK2_MESSAGE_ADDTWOINTS_H
