// Generated by gencpp from file task3/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_ADDTWOINTS_H
#define TASK3_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <task3/AddTwoIntsRequest.h>
#include <task3/AddTwoIntsResponse.h>


namespace task3
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace task3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task3::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::task3::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::task3::AddTwoInts > {
  static const char* value()
  {
    return "task3/AddTwoInts";
  }

  static const char* value(const ::task3::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::task3::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::task3::AddTwoInts >
template<>
struct MD5Sum< ::task3::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task3::AddTwoInts >::value();
  }
  static const char* value(const ::task3::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::AddTwoIntsRequest> should match
// service_traits::DataType< ::task3::AddTwoInts >
template<>
struct DataType< ::task3::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::task3::AddTwoInts >::value();
  }
  static const char* value(const ::task3::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task3::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::task3::AddTwoInts >
template<>
struct MD5Sum< ::task3::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task3::AddTwoInts >::value();
  }
  static const char* value(const ::task3::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::AddTwoIntsResponse> should match
// service_traits::DataType< ::task3::AddTwoInts >
template<>
struct DataType< ::task3::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::task3::AddTwoInts >::value();
  }
  static const char* value(const ::task3::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK3_MESSAGE_ADDTWOINTS_H
